(with-eval-after-load 'gptel
  (setq gptel-track-media t
    gptel-include-reasoning-in-response t
    gptel-include-tool-results t
    )
  (gptel-make-ollama "Ollama"             ;Any name of your choosing
    :host "localhost:11434"               ;Where it's running
    :stream t                             ;Stream responses
    :models '(llama3.1:8b
               qwen2.5:0.5b
               nomic-embed-text:latest
               qwen2.5:7b
               gemma3:latest
               promethean-planner:latest
               qwen2.5-coder:7b
               qwen3:8b
               qwen3:4b
               gemma2:2b
               qwen2.5:3b-instruct
               llama3.2:latest))          ;List of models
  (gptel-make-openai "OpenAI Streaming"           ;Any name of your choosing
    :host "api.openai.com"         ;OpenAI's API host
    :stream t                       ;Stream responses

    :key (auth-source-pick-first-password :host "api.openai.com")
    :models '(gpt-4-turbo
               gpt-4
               gpt-3.5-turbo
               gpt-3.5-turbo-16k
               gpt-5-nano
               gpt-4.1-mini
               gpt-4.1
               gpt-4.5-preview
               gpt-5-chat-latest
               gpt-5-codex

               )
    )
  (gptel-make-openai "OpenAI Non-streaming"           ;Any name of your choosing
    :host "api.openai.com"         ;OpenAI's API host
    :stream nil                       ;Stream responses

    :key (auth-source-pick-first-password :host "api.openai.com")
    :models '(gpt-4-turbo
               gpt-4
               gpt-5
               gpt-3.5-turbo
               gpt-3.5-turbo-16k
               gpt-5-nano
               gpt-4.1-mini
               gpt-4.1
               gpt-4.5-preview
               gpt-5-chat
               gpt-5-codex))
  (gptel-make-openai "z.ai"
    :host "api.z.ai"
    :stream t
    :key (auth-source-pick-first-password :host "z.ai")
    :endpoint "/api/coding/paas/v4"
    :models `(glm-4.6 glm-4.5)))

;; Failed to start server haiku-rag: (error Keyword argument :cwd not one of (:command :args :url :env :initial-callback :tools-callback :prompts-callback :resources-callback :resources-templates-callback :error-callback :syncp))
;; Failed to start server npm-helper: (error Keyword argument :cwd not one of (:command :args :url :env :initial-callback :tools-callback :prompts-callback :resources-callback :resources-templates-callback :error-callback :syncp))
;; Failed to start server playwright: (error Keyword argument :cwd not one of (:command :args :url :env :initial-callback :tools-callback :prompts-callback :resources-callback :resources-templates-callback :error-callback :syncp))
;; Failed to start server serena: (error Keyword argument :cwd not one of (:command :args :url :env :initial-callback :tools-callback :prompts-callback :resources-callback :resources-templates-callback :error-callback :syncp))
;; Failed to start server ts-ls-lsp: (error Keyword argument :cwd not one of (:command :args :url :env :initial-callback :tools-callback :prompts-callback :resources-callback :resources-templates-callback :error-callback :syncp))
;; AUTO-GENERATED by mk.mcp-cli -- edits will be overwritten.
(with-eval-after-load 'mcp)
